language: go

addons:
  apt:
    sources:
      - sourceline: 'ppa:git-core/ppa'
    packages:
      - git

matrix:
  include:
    - go: 1.6
    - go: 1.7
    - go: 1.8
      env: RUN_INTEGRATION_TESTS=true

