package main

import (
	"bytes"
	"gopkg.in/yaml.v2"
	"io"
)

type source struct {
	Basedir string
	Prefix  string
	Remote  string
}

type r10kConfig struct {
	Cachedir string
	Sources  map[string]source
}

func parseConfig(file io.Reader) (r10kConfig, error) {
	t := r10kConfig{}

	buf := new(bytes.Buffer)
	buf.ReadFrom(file)

	err := yaml.Unmarshal(buf.Bytes(), &t)
    if err != nil {
      return nil, error
    }

	return t, nil
}
